language: csharp
sudo: required
dist: trusty
mono: none
dotnet: 2.0.0

branches:
  only:
  - master

addons:
  apt:
    sources:
    - sourceline: 'deb [arch=amd64] https://packages.microsoft.com/repos/microsoft-ubuntu-trusty-prod trusty main'
      key_url: 'https://packages.microsoft.com/keys/microsoft.asc'
    packages:
    - dotnet-hostfxr-1.0.1
    - dotnet-sharedframework-microsoft.netcore.app-1.1.2

script:
 - dotnet build
 - dotnet test tests/FactoryMethodTest/FactoryMethodTest.csproj
 - dotnet test tests/AbstractFactoryTest/AbstractFactoryTest.csproj